name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm and Node
        uses: pnpm/setup@v2
        with:
          runtime: node@lts
          cache: true

      - name: Lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm and Node
        uses: pnpm/setup@v2
        with:
          runtime: node@lts
          cache: true

      - name: Typecheck
        run: pnpm typecheck

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [lts]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm and Node ${{ matrix.node }}
        uses: pnpm/setup@v2
        with:
          runtime: node@${{ matrix.node }}
          cache: true

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
